### ISSUE TITLE
Cannot open documentation

### ISSUE THREAD

**Issue by LauKo20** [pyxnat/pyxnat#175] opened 2023-08-07 12:00 UTC
Hi, the link to the documentation is not working. I get the error message "File not found - The site configured at this address does not contain the requested file. "

Thanks in advance

**Comment by locastre** [comment] 2023-08-11 00:46
Documentation still unavailable at https://pyxnat.github.io/pyxnat/

**Comment by jhuguetn** [comment] 2023-08-22 10:35
Thanks both, @LauKo20 and @locastre for bringing that out.  

I believe the cause is in the building step of the documentation pages, which is failing due to the version of Sphinx package installed by the `docs` CI workflow. Sphinx 7.x has [deprecated](https://github.com/sphinx-doc/sphinx/pull/11381) the `style` key which is still used by our docs theme (`standford` theme). See similar raised issues [here](https://github.com/readthedocs/readthedocs.org/issues/10279) and [here](https://github.com/kivy/kivy/issues/8230). 

I will for now pin Sphinx<7.0 to bring documentation back to life and we'll explore in a future if we can migrate to another theme which does support newer versions of Sphinx and thus remove the Sphinx version restriction workaround.

**Comment by jhuguetn** [comment] 2023-08-22 11:44
[Docs](https://pyxnat.github.io/pyxnat/) are back to life now. Closing this issue, thank you. 

Btw, I see now that our Sphinx theme repo (https://github.com/DrJimFan/Sphinx-theme) has been archived just few months ago and is no longer maintained/active. More arguments for migrating to another theme package (the RTDs [theme](https://github.com/readthedocs/sphinx_rtd_theme), for instance).

**Closed by jhuguetn** 2023-08-22 11:44 UTC
